# Copy the configuration below and add it to your
# ~/.config/kitty/kitty.conf file

## Root Loops color scheme
## via https://rootloops.sh?sugar=6&colors=0&sogginess=10&flavor=1&fruit=10&milk=0

# The basic colors
background              #111111
foreground              #ebdbb2
selection_background    #f5f1ff
selection_foreground    #0a001a

# Cursor colors
cursor_text_color       #1e1e2e
cursor                  #ebdbb2

# URL underline color when hovering with mouse
url_color               #999999

# Kitty window border colors
active_border_color     #bb92ff
inactive_border_color   #6a01bb
bell_border_color       #848484

# Tab bar colors
active_tab_foreground   #f5f1ff
active_tab_background   #0a001a
inactive_tab_foreground #2f0058
inactive_tab_background #bb92ff
tab_bar_background      #0a001a

# Colors for marks (marked text in the terminal)
mark1_foreground #f5f1ff
mark1_background #999999
mark2_foreground #f5f1ff
mark2_background #999999
mark3_foreground #f5f1ff
mark3_background #999999

# The 16 terminal colors
# black
color0 #261d35
color8 #584875

# red
color1 #bb676f
color9 #cf7e85

# green
color2  #6d9059
color10 #80a66b

# yellow
color3  #a07d4c
color11 #b7915c

# blue
color4  #5c86bc
color12 #739bcf

# magenta
color5  #9e6db4
color13 #b284c6

# cyan
color6  #4e9190
color14 #5ea7a7

# white
color7  #b2a2d1
color15 #e5dff1



shell_integration no-cursor
font_size 18.0
background_opacity 0.7
enable_audio_bell no


